package com.autosre.agent.model;

import java.time.Instant;
import java.util.List;

/**
 * Represents a predictive alert generated by the PredictiveAgent when
 * trend analysis indicates a likely failure within 15-30 minutes.
 *
 * <p>Bounded context: {@code ai-agent-service}</p>
 *
 * @param alertId unique identifier for this predictive alert
 * @param serviceId the affected service identifier
 * @param predictedFailureType the type of failure predicted (e.g., "memory_exhaustion", "disk_fill")
 * @param predictedTimeMinutes estimated minutes until failure
 * @param confidenceScore confidence in the prediction (0.0 to 1.0)
 * @param currentMetricValue current value of the metric being analyzed
 * @param projectedMetricValue predicted value at failure time
 * @param affectedComponents list of components likely to be affected
 * @param recommendedActions suggested actions to prevent the failure
 * @param createdAt when this alert was generated
 */
public record PredictiveAlert(
        String alertId,
        String serviceId,
        String predictedFailureType,
        int predictedTimeMinutes,
        double confidenceScore,
        double currentMetricValue,
        double projectedMetricValue,
        List<String> affectedComponents,
        List<String> recommendedActions,
        Instant createdAt
) {

    /**
     * Creates a predictive alert with generated ID and current timestamp.
     */
    public static PredictiveAlert create(
            String serviceId,
            String predictedFailureType,
            int predictedTimeMinutes,
            double confidenceScore,
            double currentMetricValue,
            double projectedMetricValue,
            List<String> affectedComponents,
            List<String> recommendedActions) {

        return new PredictiveAlert(
                java.util.UUID.randomUUID().toString(),
                serviceId,
                predictedFailureType,
                predictedTimeMinutes,
                confidenceScore,
                currentMetricValue,
                projectedMetricValue,
                affectedComponents,
                recommendedActions,
                Instant.now()
        );
    }

    /**
     * Returns true if this is a high-confidence prediction.
     */
    public boolean isHighConfidence() {
        return confidenceScore >= 0.75;
    }

    /**
     * Returns true if the predicted failure is imminent (within 15 minutes).
     */
    public boolean isImminent() {
        return predictedTimeMinutes <= 15;
    }
}